### ISSUE TITLE
提议批评《精通HTML5 + CSS3+JavaScript网页设计》

### ISSUE THREAD

**Issue by Jiasm** [EarsEyesMouth/books-blacklist-references#1]
<table>
  <tr>
    <th width=120 align=right>书名</th>
    <td>精通HTML5 + CSS3+JavaScript网页设计</td>
  </tr>
  <tr>
    <th width=120 align=right>封面</th>
    <td><img src=https://img3.doubanio.com/lpic/s11315061.jpg height=80/></td>
  </tr>
  <tr>
    <th align=right>作者</th>
    <td>刘增杰 等</td>
  </tr>
  <tr>
    <th align=right>出版社</th>
    <td>清华大学出版社</td>
  </tr>
  <tr>
    <th align=right>出版年月</th>
    <td>2012-07-01</td>
  </tr>
  <tr>
    <th align=right>ISBN</th>
    <td>9787302289562</td>
  </tr>
  <tr>
    <th align=right>建议</th>
    <td>列入黑名单</td>
  </tr>
  <tr>
    <th align=right>评价</th>
    <td>本书所涉及知识点肤浅，书中错字，无效代码略多，配套视频资料更为敷衍（听不懂的方言）</td>
  </tr>
</table>

**Comment by alexinea** [comment]
赞同

**Comment by BeiMeng** [comment]
赞同

**Comment by xingwen1987** [comment]
赞同

**Comment by misaya** [comment]
竟然还有方言.

**Comment by alexinea** [comment]
经黑衣人小组（10人）投票：5人赞同、3人反对、2人弃权，本书不满60%票数，故提议未通过。

发起人可重新发起本提议，并在14天内收集到15票赞同票后，重新进入黑衣人投票环节。

**Comment by alexinea** [comment]
流程结束。
